# Generated by Django 5.2.4 on 2025-08-01 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('reading_correct_answers', models.PositiveIntegerField(default=0)),
                ('listening_correct_answers', models.PositiveIntegerField(default=0)),
                ('speaking_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('writing_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OverallScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_band', models.DecimalField(decimal_places=1, editable=False, max_digits=3)),
                ('listening_band', models.DecimalField(decimal_places=1, editable=False, max_digits=3)),
                ('overall_band', models.DecimalField(decimal_places=1, editable=False, max_digits=3)),
                ('test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_score', to='users.testresult')),
            ],
        ),
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='users.user'),
        ),
    ]
