# Generated by Django 5.2.4 on 2025-07-28 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(help_text='Passage 1, 2, 3 uchun tartib raqami')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false_not_given', 'True/False/Not Given'), ('matching_headings', 'Matching Headings'), ('sentence_completion', 'Sentence Completion'), ('summary_completion', 'Summary Completion'), ('diagram_labeling', 'Diagram Labeling'), ('short_answer', 'Short Answer')], max_length=50)),
                ('question_text', models.TextField()),
                ('question_number', models.PositiveIntegerField(help_text='Question number in the test')),
                ('options', models.JSONField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('diagram_labels', models.JSONField(blank=True, null=True)),
                ('paragraph_mapping', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.JSONField(help_text='Correct answer(s), format depends on question type')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testapp.passage')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='testapp.readingtest'),
        ),
    ]
