# Generated by Django 5.2.4 on 2025-07-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='instruction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.TextField(default=''),
        ),
    ]
