# Generated by Django 5.2.4 on 2025-07-28 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_passage_instruction_question_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='instruction',
        ),
        migrations.CreateModel(
            name='QuestionInstructionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('start_question', models.PositiveIntegerField()),
                ('end_question', models.PositiveIntegerField()),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_groups', to='testapp.passage')),
            ],
        ),
    ]
