# Generated by Django 5.2.4 on 2025-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_question_instruction_questioninstructiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='QuestionInstructionGroup',
        ),
    ]
