# Generated by Django 5.2.4 on 2025-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_question_instruction_delete_questioninstructiongroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True, default='', null=True, unique=True),
        ),
    ]
