# Generated by Django 5.2.4 on 2025-07-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_question_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SpeakingPart3Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part3_questions', to='testapp.speakingtest')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPart2CueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Full cue card prompt with bullet points')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part2_cue_card', to='testapp.speakingtest')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPart1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part1_questions', to='testapp.speakingtest')),
            ],
        ),
        migrations.CreateModel(
            name='UserSpeakingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3')], max_length=10)),
                ('question_text', models.TextField()),
                ('audio_file', models.FileField(upload_to='speaking_responses/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.speakingtest')),
            ],
        ),
    ]
