# Generated by Django 5.2.4 on 2025-07-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_speakingtest_alter_question_instruction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Task 2 essay prompt')),
                ('sample_answer', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task2', to='testapp.writingtest')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Task 1 question (e.g. graph/letter description)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing/task1/')),
                ('sample_answer', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task1', to='testapp.writingtest')),
            ],
        ),
    ]
