# Generated by Django 5.2.4 on 2025-07-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_writingtest_writingtask2_writingtask1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSpeakingResponse',
        ),
    ]
