# Generated by Django 5.2.4 on 2025-07-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_delete_userspeakingresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveIntegerField(help_text='Section 1, 2, 3, or 4')),
                ('instruction', models.TextField(blank=True, null=True)),
                ('start_time', models.DurationField(blank=True, help_text='Optional: start time in audio', null=True)),
                ('end_time', models.DurationField(blank=True, help_text='Optional: end time in audio', null=True)),
            ],
            options={
                'ordering': ['section_number'],
            },
        ),
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='listening/audio_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('form_completion', 'Form Completion'), ('table_completion', 'Table Completion'), ('note_completion', 'Note Completion'), ('map_labelling', 'Map Labelling'), ('matching', 'Matching'), ('sentence_completion', 'Sentence Completion'), ('short_answer', 'Short Answer')], max_length=50)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, help_text='For multiple choice, etc.', null=True)),
                ('correct_answer', models.JSONField(help_text='Correct answer(s), format depends on question type')),
                ('instruction', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testapp.audiosection')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.AddField(
            model_name='audiosection',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='testapp.listeningtest'),
        ),
    ]
