# Generated by Django 5.2.4 on 2025-07-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_audiosection_listeningtest_listeningquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosection',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='audiosection',
            name='start_time',
        ),
        migrations.AddField(
            model_name='audiosection',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='listening/sections/'),
        ),
    ]
