# Generated by Django 5.2.4 on 2025-07-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_remove_audiosection_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosection',
            name='end_time',
            field=models.DurationField(blank=True, help_text='Optional: end time in audio', null=True),
        ),
        migrations.AddField(
            model_name='audiosection',
            name='start_time',
            field=models.DurationField(blank=True, help_text='Optional: start time in audio', null=True),
        ),
    ]
