# Generated by Django 5.2.4 on 2025-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_audiosection_end_time_audiosection_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='map_image',
            field=models.ImageField(blank=True, help_text='Only used for map labelling questions', null=True, upload_to='listening/maps/'),
        ),
        migrations.AlterField(
            model_name='listeningtest',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='listening/audio_files/'),
        ),
    ]
