# Generated by Django 5.2.4 on 2025-07-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_listeningquestion_map_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningtest',
            name='audio_file',
        ),
    ]
