# Generated by Django 5.2.4 on 2025-07-31 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_remove_listeningtest_audio_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listeningquestion',
            unique_together={('section', 'question_number')},
        ),
        migrations.CreateModel(
            name='ListeningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.JSONField(help_text='List of column headers')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='testapp.listeningquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_data', models.JSONField(help_text='List of row items, include [[n]] where needed')),
                ('order', models.PositiveIntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='testapp.listeningtable')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListeningTableAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='The number inside [[n]]')),
                ('correct_answer', models.CharField(max_length=255)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testapp.listeningtable')),
            ],
            options={
                'unique_together': {('table', 'number')},
            },
        ),
    ]
