# Generated by Django 5.2.4 on 2025-08-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_alter_listeningquestion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingpart1question',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='speakingpart3question',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
