# Generated by Django 5.2.4 on 2025-08-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_speakingpart1question_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingtask1',
            name='sample_answer',
        ),
        migrations.RemoveField(
            model_name='writingtask2',
            name='sample_answer',
        ),
    ]
